### ISSUE TITLE
how to auth my argo tunnel?

### ISSUE THREAD

**Issue by firefoxOnFire** [fscarmen2/X-for-Glitch#12]
I am not able to get the token. I have cloudflared argo enabled.

**Comment by fscarmen** [comment]
https://github.com/fscarmen/ArgoX/blob/main/README.md#argo-json-%E7%9A%84%E8%8E%B7%E5%8F%96

**Comment by fscarmen2** [comment]
https://github.com/fscarmen/ArgoX/blob/main/README.md#argo-json-%E7%9A%84%E8%8E%B7%E5%8F%96

https://github.com/fscarmen/ArgoX/blob/main/README.md#argo-token-%E7%9A%84%E8%8E%B7%E5%8F%96

**Comment by firefoxOnFire** [comment]
Thanks. On glitch, people can see my code. Any way to avoid this??
I dont want to share my credentials. I have only one account.

**Comment by fscarmen2** [comment]
Yes，you can put all the environment to the file `.env`

**Comment by firefoxOnFire** [comment]
> Yes，you can put all the environment to the file `.env`

still it is writing those credentials to root directory. Today i realized.

**Comment by fscarmen2** [comment]
Both are ok.  Ths newest tutorial is set the environment variables in the file .env

**Comment by firefoxOnFire** [comment]
> Both are ok. Ths newest tutorial is set the environment variables in the file .env

oh, I didn't try the newest commit. I will try. Thanks for your effort.
