### ISSUE TITLE
部署后秒封-【结论：如果是导入部署话，把 fscarmen 相关的去掉即可】

### ISSUE THREAD

**Issue by lovelygfj** [fscarmen2/X-for-Glitch#14]
还请大佬看看能否伪装一下
谢谢

**Comment by fscarmen2** [comment]
把我的fscarmen去掉，或者改为其他的都可以

**Comment by lovelygfj** [comment]
好使了
需要把您上游的那些文件fork，然后改成自己fork的地址手动上传就行

**Comment by k0baya** [comment]
今天早上突然被封禁，尝试重新部署后发现，目前即便是上传文件的方式进行部署，也需要把`package.json`和`server.js`两个文件中的`fscarmen`字样也一并替换掉才行。最好是自己再fork一份相关文件的仓库，把其中的链接替换为自己的。

**Comment by fscarmen2** [comment]
> 今天早上突然被封禁，尝试重新部署后发现，目前即便是上传文件的方式进行部署，也需要把`package.json`和`server.js`两个文件中的`fscarmen`字样也一并替换掉才行。最好是自己再fork一份相关文件的仓库，把其中的链接替换为自己的。

可以用 "use this template"到自己仓库后，之后搜索所有的 fscarmen 去掉即可。

**Comment by FrostLunar** [comment]
没用，现在都部署不了了
