### ISSUE TITLE
运行时间久了，磁盘空间不足

### ISSUE THREAD

**Issue by yidasanqian** [fscarmen2/X-for-Glitch#16]
glitch服务器/app/.git目录占用过大，导致磁盘空间不足，应该是哪个git下载解压导致的，请修复

**Comment by fscarmen2** [comment]
这个目录应该与脚本无关，里面都有些什么文件，我也发现磁盘空间不足的问题，但没有详细查是哪里出问题，不太好查，只有200 MB给用。如果是这个目录下的，我处理一下，定时删除该目录。

**Comment by yidasanqian** [comment]
> 这个目录应该与脚本无关，里面都有些什么文件，我也发现磁盘空间不足的问题，但没有详细查是哪里出问题，不太好查，只有200 MB给用。如果是这个目录下的，我处理一下，定时删除该目录。

你可以进入这个目录下看看，会一直增加文件大小，不知道什么原因，我之前删除了，现在又出现了，加个定时删除该目录的脚本应该可以解决磁盘空间不足的问题

**Comment by fscarmen2** [comment]
这里的文件夹我不知道是什么来的，不太敢乱删。

**Comment by fscarmen2** [comment]
能不能再细致点查到哪些文件变大或者增加？

**Comment by fscarmen2** [comment]
> /app/.git

我现在运行了 `rm -rf /app/.git; touch /app/.git`，先删除了该目录，再强行建一个文件，让系统建不了该目录和放数据，过几天看看是否正常，如果正常，再更新一下脚本。你也可以手动试试

**Comment by yidasanqian** [comment]
> > /app/.git
> 
> 我现在运行了 `rm -rf /app/.git; touch /app/.git`，先删除了该目录，再强行建一个文件，让系统建不了该目录和放数据，过几天看看是否正常，如果正常，再更新一下脚本。你也可以手动试试

嗯，我试试

**Comment by fscarmen2** [comment]
已处理，在 entrypoint.sh  的最后面改为
```
generate_autodel() {
  cat > auto_del.sh <<EOF
while true; do
  rm -rf /app/.git
  sleep 5
done
EOF
}

......
generate_autodel

......
[ -e auto_del.sh ] && bash auto_del.sh
```
