### ISSUE TITLE
连不通，手机小火箭显示站点链接不安全,不知道配置问题还是啥问题?

### ISSUE THREAD

**Issue by formating** [fscarmen2/X-for-Glitch#18]
进程应该都起来了

<img width="1111" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/272970/0d7b8309-06aa-4535-ba6e-ce0c9f70d27e">

端口看起来也都起来了

<img width="1002" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/272970/56ef329c-6c67-4908-9eb6-a25fd096384c">

这个应该是tunnel，看起来也起来了

<img width="1631" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/272970/af29bac4-a85e-446a-9a7a-f14e15e0b905">

用你在别人的问题里面的方式测试了一下没有hostname

<img width="788" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/272970/deecb98e-107a-41c4-9e90-5a896fd56e1f">

tunnel设置的域名也就是ARGO_DOMIAN设置的值访问是这个结果:

<img width="552" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/272970/70c52140-b4e1-4c41-917b-0e2ac7dca783">

.env的环境变量设置:

<img width="601" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/272970/621e97e8-e9e9-472c-af95-6320065f7a41">

我不知道是不是我的设置问题导致的...ARGO_AUTH用你的便捷方式生成的json,ARGO_DOMIAN设置的是NS托管在CF里面的域名

客户端配置在macos里面的clashx

<img width="448" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/272970/62b3bbfc-e8cb-4dcf-a4ff-ecee17778f68">

手机小火箭里面:

跟这个差不多照着list里面配置的.麻烦大佬帮忙看看到底是哪里理解有问题还是配置上出岔子了。。。另外那个优选IP，icook.hk这个域名。。是啥意思呢？不太理解

**Comment by formating** [comment]
是我客户端配置的问题，手机端小火箭配置也有问题，换v2rayXS可以了，不知道是不是clashX配置的问题，谢谢作者提供这么棒的工具

**Comment by fscarmen2** [comment]
我这里小火箭vless链接可以呀，你的服务起来了，如隧道也通的话，检查客户端的配置
![IMG_4602](https://github.com/fscarmen2/X-for-Glitch/assets/92626977/2eb492bc-4675-44d9-a03b-cb149eade353)
![IMG_4603](https://github.com/fscarmen2/X-for-Glitch/assets/92626977/ca1aa771-dd92-4865-ab08-d953ab1232c4)

**Comment by fscarmen2** [comment]
> 进程应该都起来了
> 
> <img alt="image" width="1111" src="https://user-images.githubusercontent.com/272970/254814764-0d7b8309-06aa-4535-ba6e-ce0c9f70d27e.png">
> 端口看起来也都起来了
> 
> <img alt="image" width="1002" src="https://user-images.githubusercontent.com/272970/254814523-56ef329c-6c67-4908-9eb6-a25fd096384c.png">
> 这个应该是tunnel，看起来也起来了
> 
> <img alt="image" width="1631" src="https://user-images.githubusercontent.com/272970/254815740-af29bac4-a85e-446a-9a7a-f14e15e0b905.png">
> 用你在别人的问题里面的方式测试了一下没有hostname
> 
> <img alt="image" width="788" src="https://user-images.githubusercontent.com/272970/254815743-deecb98e-107a-41c4-9e90-5a896fd56e1f.png">
> tunnel设置的域名也就是ARGO_DOMIAN设置的值访问是这个结果:
> 
> <img alt="image" width="552" src="https://user-images.githubusercontent.com/272970/254819902-70c52140-b4e1-4c41-917b-0e2ac7dca783.png">
> .env的环境变量设置:
> 
> <img alt="image" width="601" src="https://user-images.githubusercontent.com/272970/254818729-621e97e8-e9e9-472c-af95-6320065f7a41.png">
> 我不知道是不是我的设置问题导致的...ARGO_AUTH用你的便捷方式生成的json,ARGO_DOMIAN设置的是NS托管在CF里面的域名
> 
> 客户端配置在macos里面的clashx
> 
> <img alt="image" width="448" src="https://user-images.githubusercontent.com/272970/254818813-62b3bbfc-e8cb-4dcf-a4ff-ecee17778f68.png">
> 手机小火箭里面:
> 
> 跟这个差不多照着list里面配置的.麻烦大佬帮忙看看到底是哪里理解有问题还是配置上出岔子了。。。另外那个优选IP，icook.hk这个域名。。是啥意思呢？不太理解

把icook.hk换成适合你的优选ip
