### ISSUE TITLE
Isn't it supposed to work with no personal cloudflare Argo?

### ISSUE THREAD

**Issue by mewchore** [fscarmen2/X-for-Glitch#3]
I have deleted lines 4 through 12 because I did not have nezha & Argo auth. The description says it will give a custom temporary link, but the configurations generated in `/list` do not have anything in their "host" and "sni" fields.

**Comment by fscarmen2** [comment]
Ths . The issue is a bug.  You can add commands as follow in entrypoint.sh.
```
    sleep 5
    ARGO_DOMAIN=\$(cat argo.log | grep -o "info.*https://.*trycloudflare.com" | sed "s@.*https://@@g" | tail -n 1)
```

![image](https://user-images.githubusercontent.com/92626977/220891163-793e08b0-e9e0-46dc-8630-c118bf5b968f.png)

**Comment by fscarmen2** [comment]
Does it work now?

**Comment by mewchore** [comment]
Yes sir! I uploaded the new `entrypoint.sh` file that you had modified. Thank you!

**Comment by fscarmen2** [comment]
This version can unlock chatGPT either . Enjoy it !
