### ISSUE TITLE
到一定时间会被关掉，无法持续保活，不知道是Glitch的机制，还是脚本的问题

### ISSUE THREAD

**Issue by lovelygfj** [fscarmen2/X-for-Glitch#4]

**Comment by fscarmen2** [comment]
应该是机制变了，建议你用第三方保活，如 https://uptimerobot.com/ 或者哪吒的功能，我迟点再看看保活那里如何处理。

**Comment by Jabi-james** [comment]
> 应该是机制变了，建议你用第三方保活，如 https://uptimerobot.com/ 或者哪吒的功能，我迟点再看看保活那里如何处理。

It
![Uploading Screenshot 2023-03-08 045808.jpg…]()
 is the Glitch mechanism

**Comment by fscarmen2** [comment]
我换了个保活的方法，看看效果，可以的话更新上去

**Comment by Jabi-james** [comment]
> I changed the method of keeping alive, see the effect, update it if possible

Ok,, How can I update? Do the procedure all over again? 

Thanks for the project ,

**Comment by fscarmen** [comment]
> > I changed the method of keeping alive, see the effect, update it if possible
> 
> Ok,, How can I update? Do the procedure all over again?
> 
> Thanks for the project ,

You can keep alive glitch by the service:　https://uptimerobot.com/

**Comment by Jabi-james** [comment]
> > > I changed the method of keeping alive, see the effect, update it if possible
> > 
> > 
> > Ok,, How can I update? Do the procedure all over again?
> > Thanks for the project ,
> 
> You can keep alive glitch by the service:　https://uptimerobot.com/

Yes, I'm using this service, added the link,  glitch gave me.

**Comment by fscarmen2** [comment]
The original method for keeping the app alive was effective, but it stopped working because Glitch imposed a restriction that prevented its own IP from accessing itself through the firewall. Today, it was discovered that the restriction has been lifted, so the original method is still valid.

原来的保活方法是有效的，后面没有更改相关代码而失效，原因是glitch官方作了限制，防火墙那里禁止了自己的IP访问自己，今天发现已经解除限制，所以原来的方法仍然可行，我今天再观察看看。

**Comment by Jabi-james** [comment]
> 

prevented its own IP from accessing itself through the firewall. 
they did that for v2ray services to stop them from working, yeah? 
Yesterday I couldn't connect with glitch at all,, I will test it and report..

**Comment by fscarmen** [comment]
是的，Glitch 是 ban 了 uptimerebot 的访问，报错 Forbidden (403)，而自保活也一时可以一时不行，也是因为官方限制自己的 IP 来访问自己，用其他的vps访问他就行了。由于我有安装哪吒，直接就用哪吒这个服务了，还可以。

**Comment by fscarmen2** [comment]
是的，Glitch 是 ban 了 uptimerebot 的访问，报错 Forbidden (403)，而自保活也一时可以一时不行，显示一样的错误，也是因为官方限制自己的 IP 来访问自己，同样的时间用其他的vps访问他的网址就行了。由于我有安装哪吒，直接就用哪吒这个服务了，还可以。

**Comment by Jabi-james** [comment]
> 

Is there something specific we should do to use nezha or it ran automatically when we start the script on glitch?

**Comment by fscarmen2** [comment]
> I might be wrong but it seems by using nezha you have to deploy it on your VPS first in order to use it on Glitch. So i just made a cron on my VPS to curl my glitch url every 1 minute to keep it alive, but my argo domain still changed after around 24 hours which means the service got rebooted and i can't figure out why.

If you have a domain hosted on Cloudflare, you can use my feature net: https://fscarmen.cloudflare.now.cc/  to apply for json, fill the ARGO_AUTH and ARGO_DOMAIN variables in entrypoint.sh, so that you can use a fixed domain name.

**Comment by Neomanbeta** [comment]
> > I might be wrong but it seems by using nezha you have to deploy it on your VPS first in order to use it on Glitch. So i just made a cron on my VPS to curl my glitch url every 1 minute to keep it alive, but my argo domain still changed after around 24 hours which means the service got rebooted and i can't figure out why.
> 
> If you have a domain hosted on Cloudflare, you can use my feature net: https://fscarmen.cloudflare.now.cc/ to apply for json, fill the ARGO_AUTH and ARGO_DOMAIN variables in entrypoint.sh, so that you can use a fixed domain name.

谢谢，我有cloudflare托管的域名，但是这个操作不知道怎么弄，有教程可以参考一下吗？

**Comment by Neomanbeta** [comment]
> > I might be wrong but it seems by using nezha you have to deploy it on your VPS first in order to use it on Glitch. So i just made a cron on my VPS to curl my glitch url every 1 minute to keep it alive, but my argo domain still changed after around 24 hours which means the service got rebooted and i can't figure out why.
> 
> If you have a domain hosted on Cloudflare, you can use my feature net: https://fscarmen.cloudflare.now.cc/ to apply for json, fill the ARGO_AUTH and ARGO_DOMAIN variables in entrypoint.sh, so that you can use a fixed domain name.

多谢，重新部署后搞定，弄的时候才发现 [Argo-Xray-JS-PaaS](https://github.com/fscarmen2/Argo-Xray-JS-PaaS)和[X-for-Glitch](https://github.com/fscarmen2/X-for-Glitch)是不同的，我说我怎么半天都没找到那两个argo的参数。

**Comment by fscarmen2** [comment]
> 多谢，重新部署后搞定，弄的时候才发现 [Argo-Xray-JS-PaaS](https://github.com/fscarmen2/Argo-Xray-JS-PaaS)和[X-for-Glitch](https://github.com/fscarmen2/X-for-Glitch)是不同的，我说我怎么半天都没找到那两个argo的参数。

理论是要一样的，[Argo-Xray-JS-PaaS](https://github.com/fscarmen2/Argo-Xray-JS-PaaS) 是万金油的通用版，而 [X-for-Glitch](https://github.com/fscarmen2/X-for-Glitch) 是针对 Glitch 的稍少改动。

只是前段时间我处理 VPS 用的 argo+xray 项目 [ArgoX](https://github.com/fscarmen/ArgoX) 是没有及时重新通用版本的项目。

最后大家可以通过以下功能网站，在不绑卡的情况下使用 Cloudflare 的 Zero Trust 服务：https://fscarmen.cloudflare.now.cc/

**Comment by fscarmen2** [comment]
> > 应该是机制变了，建议你用第三方保活，如 https://uptimerobot.com/ 或者哪吒的功能，我迟点再看看保活那里如何处理。
> 
> It is the Glitch mechanism ![Screenshot 2023-03-08 045808](https://user-images.githubusercontent.com/91572300/223596253-f5ba43ae-6a76-43b9-adbe-a03dbfbcdd10.jpg)

We can keep alive easily by Nezha.

**Comment by Neomanbeta** [comment]
> > 多谢，重新部署后搞定，弄的时候才发现 [Argo-Xray-JS-PaaS](https://github.com/fscarmen2/Argo-Xray-JS-PaaS)和[X-for-Glitch](https://github.com/fscarmen2/X-for-Glitch)是不同的，我说我怎么半天都没找到那两个argo的参数。
> 
> 感谢你的支持！
> 
> 理论是要一样的，[Argo-Xray-JS-PaaS](https://github.com/fscarmen2/Argo-Xray-JS-PaaS) 是万金油的通用版，而 [X-for-Glitch](https://github.com/fscarmen2/X-for-Glitch) 是针对 Glitch 的稍微改动。
> 
> 只是前段时间我处理 VPS 用的 argo+xray 项目 [ArgoX](https://github.com/fscarmen/ArgoX) 是没有及时更新通用版本的项目，刚刚已经更新完成了。
> 
> 最后大家可以通过以下功能网站，在不绑卡的情况下使用 Cloudflare 的 Zero Trust 服务：https://fscarmen.cloudflare.now.cc/

原来这是网址的作用是不用绑卡啊。。。我不知道，所以还是绑了卡，创建了通道以后，把billing里绑的卡再删掉，这么搞的。

**Comment by Jabi-james** [comment]
> > > It should be that the mechanism has changed. It is recommended that you use a third-party keepalive, such as https://uptimerobot.com/ or Nezha’s function. I will see how to deal with keepalive later.
> > 
> > 
> > It is the Glitch mechanism ![Screenshot 2023-03-08 045808](https://user-images.githubusercontent.com/91572300/223596253-f5ba43ae-6a76-43b9-adbe-a03dbfbcdd10.jpg)
> 
> We can keep alive easily by Nezha.

To use nezha we need a paid VPS, right? And to use Argo tunnel we need to add credit card to Cloudflare which is not possible for Iranian people ,, there is no way to do these free?
